language: ruby
bundler_args: --without development
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
script:
  - "rake lint"
  - "rake spec SPEC_OPTS='--format documentation'"
  - "rake spec"
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.0"
notifications:
  email: false
  hipchat:
    rooms:
      - secure: "NEofC2Vjcy0nw0G04UtJu6G8h6EXig0A35FDPIeoWhdeSydM+qgo96hP4Yf3\nqf/Y0psnPi1rhBMYH+fGhaTVutn8c5mynYGNnmnwUEdNSm92WOXHEpTIA74g\nLg5ZzI7eoMCsyvqPmalCYSMX+8VYyoK2WQjNJBB13viLomASYKE="
  on_success: always
  on_failure: always
