name 'evenup-rsyslog'
version '0.0.1'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Manages rsyslog.'
description 'Installs, configures, and runs the rsyslog service.'
project_page 'https://github.com/evenup/evenup-rsyslog'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
